name: Docker Image CI

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rgrsousa/seguranca_docker:${{ github.run_number }}

    - name: Docker Scout
  # You may pin to the exact commit or the version.
  # uses: docker/scout-action@f8c776824083494ab0d56b8105ba2ca85c86e4de
      uses: docker/scout-action@v1.18.2
      with:
        # Adicione esta linha
        command: cves
        image: rgrsousa/seguranca_docker:${{ github.run_number }}
        ignore-base: false # optional
        dockerhub-user: ${{ secrets.DOCKERHUB_USER }}
        dockerhub-password: ${{ secrets.DOCKERHUB_PASS }}
  


    - name: Aqua Security Trivy
       # You may pin to the exact commit or the version.
       # uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8
      uses: aquasecurity/trivy-action@0.33.1
      with:
        image-ref: rgrsousa/seguranca_docker:${{ github.run_number }}
        exit-code: 1 # optional
        severity: HIGH,CRITICAL
        # output format (table, json, template)
        format: table # optional, default is table
         
          
                 
         
                

